### ISSUE TITLE
[BUG] Same duplication bug as #3

### ISSUE THREAD

**Issue by jacobthemagicalpanda** [ranaldsgift/KefinTweaks#6]
I am also having the issue mentioned in issue #3. I am not having the button duplicate but the sections duplicate like he showed in this video: https://youtu.be/mGJp25-3Hzc. I just installed everything today so everything should be up to date. I am on 10.11.1. It happened with infinite scroll on and off.

<img width="3437" height="1272" alt="Image" src="https://github.com/user-attachments/assets/aceb2a08-6e8a-4358-9b15-2d3a93197d67" />

**Comment by ranaldsgift** [comment]
OK thank you! I will look into it, but if it's an issue specifically related to 10.11.1 (I don't necessarily think it is), then it may be a bit longer before it is fixed. 

Either way I will let you know probably later today or tomorrow. Thanks for reporting, and sorry for the inconvenience!

**Comment by jacobthemagicalpanda** [comment]
I actually just set all sections to false in the config and there are no duplicates now but all the sections are showing up. So this is a workaround for now but setting them all to false and them still showing up seems like something is wrong

<img width="844" height="544" alt="Image" src="https://github.com/user-attachments/assets/fbe6bde7-5cfd-4ccc-84b3-b3b7ff54f069" />

<img width="3440" height="1273" alt="Image" src="https://github.com/user-attachments/assets/a4356564-b191-4841-88fe-efee0787eeff" />

Edit: on a full CTRL+F5 it looks like even though all sections are set to false for homescreen customization they are all still there and duplicated

**Comment by ranaldsgift** [comment]
OK, that's hilarious and thanks so much for reporting this! Looking into it today! I'll be pushing an update this weekend for sure.

Thanks again

**Comment by ranaldsgift** [comment]
@jacobthemagicalpanda Let me know if you experience this issue with the latest 0.2.0 release. Thanks!

**Comment by jacobthemagicalpanda** [comment]
So I tested it and for me, the duplication seems to be resolved. I did have it happen for me once on my phone but I closed the app and opened it back up and it was fixed. However, I had one of my users that was still having the duplication issue but with it only duplicating once so it shows up twice on their side. One thing I also noticed is the sections do not seem to be updating. The new items when I first installed it are still showing as the new items now even though I have installed newer things since then. Also this may be a bug with the Javascript injector but I do not think any changes to the script are taking. I turn on infinite scroll and it doesn't apply. Also if I uncheck enable in javascript injector it is still applied. If I fully delete the script from JS injector it is still applied. I have to fully uninstall JS injector to get it to remove from my Jellyfin instance. Please let me know if that is a JS injector bug and I can submit it there.

**Comment by ranaldsgift** [comment]
@jacobthemagicalpanda 

1. Duplication bug still appearing for your friend will be difficult to diagnose. If they can provide console logs filtered with [KefinTweaks it might be possible.
2. The "new items" are you referring to the sections "New Movies" and "New Episodes"? Just to be sure, these sections display Movies that have a release date in the past 30 days (sorted by Date Added on your server), and Episodes which have a release date in the past week. You will have to describe the behavior you are seeing in a bit more detail for me to determine what is going on here.
3. The JS Injector plugin bug sounds very very....strange. I assume you are refreshing the page between saving the JS Injector plugin or removing it from the plugin. This one sounds really strange and it will probably be easier to chat via Discord to solve it.

You can find me in the Jellyfin Community Discord https://discord.gg/v7P9CAvCKZ my username is HighImKevin.

**Comment by ranaldsgift** [comment]
As we've discussed this on Discord, I think I can close the issue here. Feel free to re-open if you experience any issues like the ones mentioned.
